version: "3"

tasks:
  default:
    cmds:
      - task: dev

  docs:
    desc: Gera a documentação do Swagger
    silent: true
    cmds:
      - swag init -d cmd/api,internal -g main.go --parseDependency --parseInternal
      - echo "Swagger gerado com sucesso! 📄"

  dev:
    desc: Roda a aplicação com hot-reload via Air
    deps: [docs]
    cmds:
      - air --build.cmd "go build -o ./bin/api.exe ./cmd/api" --build.bin "./bin/api.exe"

  migrate:
    desc: Roda as migrações do banco de dados
    cmds:
      - go run ./cmd/terndotenv/main.go

  migrate_drop:
    desc: Dropa as migrações do banco de dados
    cmds:
      - go run ./cmd/terndotenv/main.go -drop {{.CLI_ARGS}}

  migrate_new:
    desc: Cria uma nova migration. Uso -> task migrate_new -- nome_da_migration
    cmds:
      - tern new -m ./internal/store/pgstore/migrations {{.CLI_ARGS}}

  sqlcgenerate:
    desc: Generate queries with sqlc
    cmds:
      - sqlc  generate -f ./internal/store/pgstore/sqlc.yaml
      - echo "Queries generated successfully!"

  clean:
    cmds:
      - rm -rf bin
      - rm -rf tmp
