// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_requests.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessRequest = `-- name: CreateAccessRequest :one
INSERT INTO access_requests (
  user_id,
  condominium_id,
  apartment_id
) VALUES (
  $1,
  $2,
  $3
) RETURNING id
`

type CreateAccessRequestParams struct {
	UserID        uuid.UUID `json:"user_id"`
	CondominiumID uuid.UUID `json:"condominium_id"`
	ApartmentID   uuid.UUID `json:"apartment_id"`
}

func (q *Queries) CreateAccessRequest(ctx context.Context, arg CreateAccessRequestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAccessRequest, arg.UserID, arg.CondominiumID, arg.ApartmentID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listPendingRequestsByCondo = `-- name: ListPendingRequestsByCondo :many
SELECT
  ar.id, ar.user_id, ar.condominium_id, ar.apartment_id, ar.status, ar.reviewed_by, ar.reviewed_at, ar.created_at, ar.updated_at,
  u.name,
  u.email,
  a.block,
  a.number
FROM access_requests ar
JOIN users u ON u.id = ar.user_id
JOIN apartments a ON a.id = ar.apartment_id
WHERE ar.condominium_id = $1 AND ar.status = 'pending'
`

type ListPendingRequestsByCondoRow struct {
	ID            uuid.UUID   `json:"id"`
	UserID        uuid.UUID   `json:"user_id"`
	CondominiumID uuid.UUID   `json:"condominium_id"`
	ApartmentID   uuid.UUID   `json:"apartment_id"`
	Status        string      `json:"status"`
	ReviewedBy    pgtype.UUID `json:"reviewed_by"`
	ReviewedAt    *time.Time  `json:"reviewed_at"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     *time.Time  `json:"updated_at"`
	Name          string      `json:"name"`
	Email         string      `json:"email"`
	Block         *string     `json:"block"`
	Number        string      `json:"number"`
}

func (q *Queries) ListPendingRequestsByCondo(ctx context.Context, condominiumID uuid.UUID) ([]ListPendingRequestsByCondoRow, error) {
	rows, err := q.db.Query(ctx, listPendingRequestsByCondo, condominiumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRequestsByCondoRow
	for rows.Next() {
		var i ListPendingRequestsByCondoRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CondominiumID,
			&i.ApartmentID,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Email,
			&i.Block,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccessRequestStatus = `-- name: UpdateAccessRequestStatus :exec
UPDATE access_requests
SET status = $2,
    reviewed_by = $3,
    reviewed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type UpdateAccessRequestStatusParams struct {
	ID         uuid.UUID   `json:"id"`
	Status     string      `json:"status"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) UpdateAccessRequestStatus(ctx context.Context, arg UpdateAccessRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updateAccessRequestStatus, arg.ID, arg.Status, arg.ReviewedBy)
	return err
}
