// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_logs.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const logAccessEntry = `-- name: LogAccessEntry :one
INSERT INTO access_logs (
  invite_id,
  condominium_id,
  authorized_by
) VALUES (
  $1,
  $2,
  $3
) RETURNING id, invite_id, condominium_id, entered_at, authorized_by
`

type LogAccessEntryParams struct {
	InviteID      uuid.UUID  `json:"invite_id"`
	CondominiumID uuid.UUID  `json:"condominium_id"`
	AuthorizedBy  *uuid.UUID `json:"authorized_by"`
}

func (q *Queries) LogAccessEntry(ctx context.Context, arg LogAccessEntryParams) (AccessLog, error) {
	row := q.db.QueryRow(ctx, logAccessEntry, arg.InviteID, arg.CondominiumID, arg.AuthorizedBy)
	var i AccessLog
	err := row.Scan(
		&i.ID,
		&i.InviteID,
		&i.CondominiumID,
		&i.EnteredAt,
		&i.AuthorizedBy,
	)
	return i, err
}
