// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createAccountWithCredentials = `-- name: CreateAccountWithCredentials :exec
INSERT INTO accounts (
  user_id,
  provider_account_id,
  provider_id,
  password_hash
) VALUES (
  $1,
  $2,
  $3,
  $4
)
`

type CreateAccountWithCredentialsParams struct {
	UserID            uuid.UUID `json:"user_id"`
	ProviderAccountID string    `json:"provider_account_id"`
	ProviderID        string    `json:"provider_id"`
	PasswordHash      []byte    `json:"password_hash"`
}

func (q *Queries) CreateAccountWithCredentials(ctx context.Context, arg CreateAccountWithCredentialsParams) error {
	_, err := q.db.Exec(ctx, createAccountWithCredentials,
		arg.UserID,
		arg.ProviderAccountID,
		arg.ProviderID,
		arg.PasswordHash,
	)
	return err
}
