// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: announcements.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcements (
  condominium_id,
  author_id,
  title,
  content
) VALUES (
  $1,
  $2,
  $3,
  $4
) RETURNING id, created_at
`

type CreateAnnouncementParams struct {
	CondominiumID uuid.UUID  `json:"condominium_id"`
	AuthorID      *uuid.UUID `json:"author_id"`
	Title         string     `json:"title"`
	Content       string     `json:"content"`
}

type CreateAnnouncementRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (CreateAnnouncementRow, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.CondominiumID,
		arg.AuthorID,
		arg.Title,
		arg.Content,
	)
	var i CreateAnnouncementRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :exec
DELETE FROM announcements
WHERE id = $1 AND condominium_id = $2
`

type DeleteAnnouncementParams struct {
	ID            uuid.UUID `json:"id"`
	CondominiumID uuid.UUID `json:"condominium_id"`
}

func (q *Queries) DeleteAnnouncement(ctx context.Context, arg DeleteAnnouncementParams) error {
	_, err := q.db.Exec(ctx, deleteAnnouncement, arg.ID, arg.CondominiumID)
	return err
}

const getAnnouncementById = `-- name: GetAnnouncementById :one
SELECT
  id, condominium_id, author_id, title, content, created_at, updated_at
FROM announcements
WHERE id = $1
`

func (q *Queries) GetAnnouncementById(ctx context.Context, id uuid.UUID) (Announcement, error) {
	row := q.db.QueryRow(ctx, getAnnouncementById, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.CondominiumID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManyAnnouncementsByCondoId = `-- name: GetManyAnnouncementsByCondoId :many
SELECT
  a.id,
  a.title,
  a.content,
  a.created_at,
  u.name AS author_name
FROM announcements a
LEFT JOIN users u ON u.id = a.author_id
WHERE a.condominium_id = $1
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type GetManyAnnouncementsByCondoIdParams struct {
	CondominiumID uuid.UUID `json:"condominium_id"`
	Limit         int32     `json:"limit"`
	Offset        int32     `json:"offset"`
}

type GetManyAnnouncementsByCondoIdRow struct {
	ID         uuid.UUID `json:"id"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	CreatedAt  time.Time `json:"created_at"`
	AuthorName *string   `json:"author_name"`
}

func (q *Queries) GetManyAnnouncementsByCondoId(ctx context.Context, arg GetManyAnnouncementsByCondoIdParams) ([]GetManyAnnouncementsByCondoIdRow, error) {
	rows, err := q.db.Query(ctx, getManyAnnouncementsByCondoId, arg.CondominiumID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetManyAnnouncementsByCondoIdRow
	for rows.Next() {
		var i GetManyAnnouncementsByCondoIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnouncement = `-- name: UpdateAnnouncement :exec
UPDATE announcements
SET title = $2,
    content = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAnnouncementParams struct {
	ID      uuid.UUID `json:"id"`
	Title   string    `json:"title"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) error {
	_, err := q.db.Exec(ctx, updateAnnouncement, arg.ID, arg.Title, arg.Content)
	return err
}
