// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apartments.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createApartment = `-- name: CreateApartment :one
INSERT INTO apartments (
  condominium_id,
  block,
  number
) VALUES (
  $1,
  $2,
  $3
) RETURNING id
`

type CreateApartmentParams struct {
	CondominiumID uuid.UUID `json:"condominium_id"`
	Block         *string   `json:"block"`
	Number        string    `json:"number"`
}

func (q *Queries) CreateApartment(ctx context.Context, arg CreateApartmentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createApartment, arg.CondominiumID, arg.Block, arg.Number)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
