// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookings.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkBookingConflict = `-- name: CheckBookingConflict :one
SELECT EXISTS (
  SELECT 1
  FROM bookings
  WHERE common_area_id = $1
  AND deleted_at IS NULL
  AND (
    (starts_at < $3 AND ends_at > $2)
  )
)
`

type CheckBookingConflictParams struct {
	CommonAreaID uuid.UUID `json:"common_area_id"`
	EndsAt       time.Time `json:"ends_at"`
	StartsAt     time.Time `json:"starts_at"`
}

func (q *Queries) CheckBookingConflict(ctx context.Context, arg CheckBookingConflictParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkBookingConflict, arg.CommonAreaID, arg.EndsAt, arg.StartsAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
  condominium_id,
  apartment_id,
  user_id,
  common_area_id,
  starts_at,
  ends_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
) RETURNING id, condominium_id, apartment_id, user_id, common_area_id, starts_at, ends_at, created_at, updated_at, deleted_at
`

type CreateBookingParams struct {
	CondominiumID uuid.UUID `json:"condominium_id"`
	ApartmentID   uuid.UUID `json:"apartment_id"`
	UserID        uuid.UUID `json:"user_id"`
	CommonAreaID  uuid.UUID `json:"common_area_id"`
	StartsAt      time.Time `json:"starts_at"`
	EndsAt        time.Time `json:"ends_at"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.CondominiumID,
		arg.ApartmentID,
		arg.UserID,
		arg.CommonAreaID,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.CondominiumID,
		&i.ApartmentID,
		&i.UserID,
		&i.CommonAreaID,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
