// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: common_areas.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createCommonArea = `-- name: CreateCommonArea :one
INSERT INTO common_areas (
  condominium_id,
  name,
  capacity,
  requires_approval
) VALUES (
  $1,
  $2,
  $3,
  $4
) RETURNING id, condominium_id, name, capacity, requires_approval
`

type CreateCommonAreaParams struct {
	CondominiumID    uuid.UUID `json:"condominium_id"`
	Name             string    `json:"name"`
	Capacity         *int32    `json:"capacity"`
	RequiresApproval bool      `json:"requires_approval"`
}

func (q *Queries) CreateCommonArea(ctx context.Context, arg CreateCommonAreaParams) (CommonArea, error) {
	row := q.db.QueryRow(ctx, createCommonArea,
		arg.CondominiumID,
		arg.Name,
		arg.Capacity,
		arg.RequiresApproval,
	)
	var i CommonArea
	err := row.Scan(
		&i.ID,
		&i.CondominiumID,
		&i.Name,
		&i.Capacity,
		&i.RequiresApproval,
	)
	return i, err
}

const getCommonAreaIdForUpdate = `-- name: GetCommonAreaIdForUpdate :one
SELECT
  id, condominium_id, name, capacity, requires_approval
FROM common_areas
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetCommonAreaIdForUpdate(ctx context.Context, id uuid.UUID) (CommonArea, error) {
	row := q.db.QueryRow(ctx, getCommonAreaIdForUpdate, id)
	var i CommonArea
	err := row.Scan(
		&i.ID,
		&i.CondominiumID,
		&i.Name,
		&i.Capacity,
		&i.RequiresApproval,
	)
	return i, err
}

const listCommonAreas = `-- name: ListCommonAreas :many
SELECT
  id, condominium_id, name, capacity, requires_approval
FROM common_areas
WHERE condominium_id = $1
`

func (q *Queries) ListCommonAreas(ctx context.Context, condominiumID uuid.UUID) ([]CommonArea, error) {
	rows, err := q.db.Query(ctx, listCommonAreas, condominiumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommonArea
	for rows.Next() {
		var i CommonArea
		if err := rows.Scan(
			&i.ID,
			&i.CondominiumID,
			&i.Name,
			&i.Capacity,
			&i.RequiresApproval,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
