// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: condominium_members.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createCondominiumMember = `-- name: CreateCondominiumMember :exec
INSERT INTO condominium_members  (
  condominium_id,
  user_id,
  role
) VALUES (
  $1,
  $2,
  $3
)
`

type CreateCondominiumMemberParams struct {
	CondominiumID uuid.UUID `json:"condominium_id"`
	UserID        uuid.UUID `json:"user_id"`
	Role          string    `json:"role"`
}

func (q *Queries) CreateCondominiumMember(ctx context.Context, arg CreateCondominiumMemberParams) error {
	_, err := q.db.Exec(ctx, createCondominiumMember, arg.CondominiumID, arg.UserID, arg.Role)
	return err
}

const getCondominiumMemberRole = `-- name: GetCondominiumMemberRole :one
SELECT
  role
FROM condominium_members
WHERE condominium_id = $1
AND user_id = $2
`

type GetCondominiumMemberRoleParams struct {
	CondominiumID uuid.UUID `json:"condominium_id"`
	UserID        uuid.UUID `json:"user_id"`
}

func (q *Queries) GetCondominiumMemberRole(ctx context.Context, arg GetCondominiumMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getCondominiumMemberRole, arg.CondominiumID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getUserMemberships = `-- name: GetUserMemberships :many
SELECT
  m.role,
  c.id as condominium_id,
  c.name as condominium_name
FROM condominium_members m
JOIN condominiums c ON c.id = m.condominium_id
WHERE user_id = $1
`

type GetUserMembershipsRow struct {
	Role            string    `json:"role"`
	CondominiumID   uuid.UUID `json:"condominium_id"`
	CondominiumName string    `json:"condominium_name"`
}

func (q *Queries) GetUserMemberships(ctx context.Context, userID uuid.UUID) ([]GetUserMembershipsRow, error) {
	rows, err := q.db.Query(ctx, getUserMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserMembershipsRow
	for rows.Next() {
		var i GetUserMembershipsRow
		if err := rows.Scan(&i.Role, &i.CondominiumID, &i.CondominiumName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
