// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: condominiums.sql

package pgstore

import (
	"context"
)

const createCondominium = `-- name: CreateCondominium :exec
INSERT INTO condominiums (
  name,
  cnpj,
  address,
  plan_type
)
VALUES (
  $1,
  $2,
  $3,
  $4
)
`

type CreateCondominiumParams struct {
	Name     string `json:"name"`
	Cnpj     string `json:"cnpj"`
	Address  string `json:"address"`
	PlanType string `json:"plan_type"`
}

func (q *Queries) CreateCondominium(ctx context.Context, arg CreateCondominiumParams) error {
	_, err := q.db.Exec(ctx, createCondominium,
		arg.Name,
		arg.Cnpj,
		arg.Address,
		arg.PlanType,
	)
	return err
}
