// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: condominiums.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createCondominium = `-- name: CreateCondominium :one
INSERT INTO condominiums (
  name,
  cnpj,
  address,
  plan_type
)
VALUES (
  $1,
  $2,
  $3,
  $4
) RETURNING id
`

type CreateCondominiumParams struct {
	Name     string `json:"name"`
	Cnpj     string `json:"cnpj"`
	Address  string `json:"address"`
	PlanType string `json:"plan_type"`
}

func (q *Queries) CreateCondominium(ctx context.Context, arg CreateCondominiumParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createCondominium,
		arg.Name,
		arg.Cnpj,
		arg.Address,
		arg.PlanType,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getCondominiumByAddress = `-- name: GetCondominiumByAddress :one
SELECT
  id, name, cnpj, address, plan_type, created_at, updated_at
FROM condominiums
WHERE address = $1
`

func (q *Queries) GetCondominiumByAddress(ctx context.Context, address string) (Condominium, error) {
	row := q.db.QueryRow(ctx, getCondominiumByAddress, address)
	var i Condominium
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cnpj,
		&i.Address,
		&i.PlanType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCondominiumById = `-- name: GetCondominiumById :one
SELECT
id, name, cnpj, address, plan_type, created_at, updated_at
FROM condominiums
WHERE id = $1
`

func (q *Queries) GetCondominiumById(ctx context.Context, id uuid.UUID) (Condominium, error) {
	row := q.db.QueryRow(ctx, getCondominiumById, id)
	var i Condominium
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cnpj,
		&i.Address,
		&i.PlanType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
