// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: condominiums.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createCondominium = `-- name: CreateCondominium :exec
INSERT INTO condominiums (
  name,
  cnpj,
  address,
  plan_type
)
VALUES (
  $1,
  $2,
  $3,
  $4
)
`

type CreateCondominiumParams struct {
	Name     string `json:"name"`
	Cnpj     string `json:"cnpj"`
	Address  string `json:"address"`
	PlanType string `json:"plan_type"`
}

func (q *Queries) CreateCondominium(ctx context.Context, arg CreateCondominiumParams) error {
	_, err := q.db.Exec(ctx, createCondominium,
		arg.Name,
		arg.Cnpj,
		arg.Address,
		arg.PlanType,
	)
	return err
}

const getCondominiumById = `-- name: GetCondominiumById :one
SELECT
id, name, cnpj, address, plan_type, created_at, updated_at
FROM condominiums
WHERE id = $1
`

func (q *Queries) GetCondominiumById(ctx context.Context, id uuid.UUID) (Condominium, error) {
	row := q.db.QueryRow(ctx, getCondominiumById, id)
	var i Condominium
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cnpj,
		&i.Address,
		&i.PlanType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
