// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (
  condominium_id,
  apartment_id,
  issued_by,
  guest_name,
  guest_type,
  starts_at,
  ends_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
) RETURNING id, condominium_id, apartment_id, issued_by, guest_name, guest_type, token, starts_at, ends_at, revoked_at, created_at
`

type CreateInviteParams struct {
	CondominiumID uuid.UUID `json:"condominium_id"`
	ApartmentID   uuid.UUID `json:"apartment_id"`
	IssuedBy      uuid.UUID `json:"issued_by"`
	GuestName     string    `json:"guest_name"`
	GuestType     string    `json:"guest_type"`
	StartsAt      time.Time `json:"starts_at"`
	EndsAt        time.Time `json:"ends_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.CondominiumID,
		arg.ApartmentID,
		arg.IssuedBy,
		arg.GuestName,
		arg.GuestType,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CondominiumID,
		&i.ApartmentID,
		&i.IssuedBy,
		&i.GuestName,
		&i.GuestType,
		&i.Token,
		&i.StartsAt,
		&i.EndsAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteById = `-- name: GetInviteById :one
SELECT
  id, condominium_id, apartment_id, issued_by, guest_name, guest_type, token, starts_at, ends_at, revoked_at, created_at
FROM invites
WHERE id = $1
`

func (q *Queries) GetInviteById(ctx context.Context, id uuid.UUID) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteById, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CondominiumID,
		&i.ApartmentID,
		&i.IssuedBy,
		&i.GuestName,
		&i.GuestType,
		&i.Token,
		&i.StartsAt,
		&i.EndsAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT
  i.id, i.condominium_id, i.apartment_id, i.issued_by, i.guest_name, i.guest_type, i.token, i.starts_at, i.ends_at, i.revoked_at, i.created_at,
  a.block,
  a.number AS apartment_number,
  u.name AS resident_name
FROM invites i
JOIN apartments a ON a.id = i.apartment_id
JOIN users u ON u.id = i.issued_by
WHERE i.token = $1
`

type GetInviteByTokenRow struct {
	ID              uuid.UUID  `json:"id"`
	CondominiumID   uuid.UUID  `json:"condominium_id"`
	ApartmentID     uuid.UUID  `json:"apartment_id"`
	IssuedBy        uuid.UUID  `json:"issued_by"`
	GuestName       string     `json:"guest_name"`
	GuestType       string     `json:"guest_type"`
	Token           uuid.UUID  `json:"token"`
	StartsAt        time.Time  `json:"starts_at"`
	EndsAt          time.Time  `json:"ends_at"`
	RevokedAt       *time.Time `json:"revoked_at"`
	CreatedAt       time.Time  `json:"created_at"`
	Block           *string    `json:"block"`
	ApartmentNumber string     `json:"apartment_number"`
	ResidentName    string     `json:"resident_name"`
}

func (q *Queries) GetInviteByToken(ctx context.Context, token uuid.UUID) (GetInviteByTokenRow, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, token)
	var i GetInviteByTokenRow
	err := row.Scan(
		&i.ID,
		&i.CondominiumID,
		&i.ApartmentID,
		&i.IssuedBy,
		&i.GuestName,
		&i.GuestType,
		&i.Token,
		&i.StartsAt,
		&i.EndsAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Block,
		&i.ApartmentNumber,
		&i.ResidentName,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT
    i.id, i.condominium_id, i.apartment_id, i.issued_by, i.guest_name, i.guest_type, i.token, i.starts_at, i.ends_at, i.revoked_at, i.created_at,
    a.block,
    a.number as apartment_number
FROM invites i
JOIN apartments a ON a.id = i.apartment_id
WHERE i.condominium_id = $1
  AND ($4::uuid IS NULL OR i.apartment_id = $4)
  AND (
      $5::boolean IS NULL
      OR ($5::boolean = TRUE AND i.ends_at > NOW() AND i.revoked_at IS NULL)
  )
ORDER BY i.created_at DESC
LIMIT $2 OFFSET $3
`

type ListInvitesParams struct {
	CondominiumID uuid.UUID  `json:"condominium_id"`
	Limit         int32      `json:"limit"`
	Offset        int32      `json:"offset"`
	ApartmentID   *uuid.UUID `json:"apartment_id"`
	OnlyActive    *bool      `json:"only_active"`
}

type ListInvitesRow struct {
	ID              uuid.UUID  `json:"id"`
	CondominiumID   uuid.UUID  `json:"condominium_id"`
	ApartmentID     uuid.UUID  `json:"apartment_id"`
	IssuedBy        uuid.UUID  `json:"issued_by"`
	GuestName       string     `json:"guest_name"`
	GuestType       string     `json:"guest_type"`
	Token           uuid.UUID  `json:"token"`
	StartsAt        time.Time  `json:"starts_at"`
	EndsAt          time.Time  `json:"ends_at"`
	RevokedAt       *time.Time `json:"revoked_at"`
	CreatedAt       time.Time  `json:"created_at"`
	Block           *string    `json:"block"`
	ApartmentNumber string     `json:"apartment_number"`
}

func (q *Queries) ListInvites(ctx context.Context, arg ListInvitesParams) ([]ListInvitesRow, error) {
	rows, err := q.db.Query(ctx, listInvites,
		arg.CondominiumID,
		arg.Limit,
		arg.Offset,
		arg.ApartmentID,
		arg.OnlyActive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvitesRow
	for rows.Next() {
		var i ListInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.CondominiumID,
			&i.ApartmentID,
			&i.IssuedBy,
			&i.GuestName,
			&i.GuestType,
			&i.Token,
			&i.StartsAt,
			&i.EndsAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.Block,
			&i.ApartmentNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvite = `-- name: RevokeInvite :exec
UPDATE invites
SET revoked_at = NOW()
WHERE id = $1 AND issued_by = $2
`

type RevokeInviteParams struct {
	ID       uuid.UUID `json:"id"`
	IssuedBy uuid.UUID `json:"issued_by"`
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) error {
	_, err := q.db.Exec(ctx, revokeInvite, arg.ID, arg.IssuedBy)
	return err
}
