// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Apartment struct {
	ID            uuid.UUID          `json:"id"`
	CondominiumID uuid.UUID          `json:"condominium_id"`
	Block         pgtype.Text        `json:"block"`
	Number        string             `json:"number"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Condominium struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Cnpj      string             `json:"cnpj"`
	Address   string             `json:"address"`
	PlanType  string             `json:"plan_type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	CondominiumID uuid.UUID          `json:"condominium_id"`
	Role          string             `json:"role"`
	Name          string             `json:"name"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	Email         string             `json:"email"`
	PasswordHash  []byte             `json:"password_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
