// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckBookingConflict(ctx context.Context, arg CheckBookingConflictParams) (bool, error)
	CheckIsResident(ctx context.Context, arg CheckIsResidentParams) (bool, error)
	CheckUserAccessToCondo(ctx context.Context, arg CheckUserAccessToCondoParams) (bool, error)
	CreateAccessRequest(ctx context.Context, arg CreateAccessRequestParams) (uuid.UUID, error)
	CreateAccountWithCredentials(ctx context.Context, arg CreateAccountWithCredentialsParams) error
	CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (CreateAnnouncementRow, error)
	CreateApartment(ctx context.Context, arg CreateApartmentParams) (uuid.UUID, error)
	CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateCommonArea(ctx context.Context, arg CreateCommonAreaParams) (CommonArea, error)
	CreateCondominium(ctx context.Context, arg CreateCondominiumParams) (uuid.UUID, error)
	CreateCondominiumMember(ctx context.Context, arg CreateCondominiumMemberParams) error
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	CreatePackage(ctx context.Context, arg CreatePackageParams) (Package, error)
	CreateResident(ctx context.Context, arg CreateResidentParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error)
	DeleteAnnouncement(ctx context.Context, arg DeleteAnnouncementParams) error
	DeleteSession(ctx context.Context, token string) error
	GetAccessRequestById(ctx context.Context, id uuid.UUID) (AccessRequest, error)
	GetAccountByUserId(ctx context.Context, userID uuid.UUID) (Account, error)
	GetAnnouncementById(ctx context.Context, id uuid.UUID) (Announcement, error)
	GetApartmentById(ctx context.Context, id uuid.UUID) (Apartment, error)
	GetApartmentsByUserId(ctx context.Context, arg GetApartmentsByUserIdParams) ([]GetApartmentsByUserIdRow, error)
	GetAreaAvailability(ctx context.Context, arg GetAreaAvailabilityParams) ([]GetAreaAvailabilityRow, error)
	GetBillById(ctx context.Context, arg GetBillByIdParams) (Bill, error)
	GetBookingById(ctx context.Context, id uuid.UUID) (GetBookingByIdRow, error)
	GetCommonAreaIdForUpdate(ctx context.Context, id uuid.UUID) (CommonArea, error)
	GetCondoAdminTokens(ctx context.Context, condominiumID uuid.UUID) ([]string, error)
	GetCondoResidentsTokens(ctx context.Context, condominiumID uuid.UUID) ([]string, error)
	GetCondominiumByAddress(ctx context.Context, address string) (Condominium, error)
	GetCondominiumById(ctx context.Context, id uuid.UUID) (Condominium, error)
	GetCondominiumMemberRole(ctx context.Context, arg GetCondominiumMemberRoleParams) (string, error)
	GetInviteById(ctx context.Context, id uuid.UUID) (Invite, error)
	GetInviteByToken(ctx context.Context, token uuid.UUID) (GetInviteByTokenRow, error)
	GetManyAnnouncementsByCondoId(ctx context.Context, arg GetManyAnnouncementsByCondoIdParams) ([]GetManyAnnouncementsByCondoIdRow, error)
	GetManyTokensByApartmentId(ctx context.Context, apartmentID uuid.UUID) ([]string, error)
	GetPackageById(ctx context.Context, id uuid.UUID) (GetPackageByIdRow, error)
	GetResidencesByUserId(ctx context.Context, userID uuid.UUID) ([]GetResidencesByUserIdRow, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserDeviceTokens(ctx context.Context, userID uuid.UUID) ([]string, error)
	GetUserMemberships(ctx context.Context, userID uuid.UUID) ([]GetUserMembershipsRow, error)
	ListBills(ctx context.Context, arg ListBillsParams) ([]Bill, error)
	ListBillsByApartmentId(ctx context.Context, arg ListBillsByApartmentIdParams) ([]Bill, error)
	ListBillsByCondominiumId(ctx context.Context, arg ListBillsByCondominiumIdParams) ([]Bill, error)
	ListBookings(ctx context.Context, arg ListBookingsParams) ([]ListBookingsRow, error)
	ListCommonAreas(ctx context.Context, condominiumID uuid.UUID) ([]CommonArea, error)
	ListCondominiunsByUserId(ctx context.Context, userID uuid.UUID) ([]ListCondominiunsByUserIdRow, error)
	ListInvites(ctx context.Context, arg ListInvitesParams) ([]ListInvitesRow, error)
	ListPackagesByApartment(ctx context.Context, arg ListPackagesByApartmentParams) ([]ListPackagesByApartmentRow, error)
	ListPackagesByCondominium(ctx context.Context, arg ListPackagesByCondominiumParams) ([]ListPackagesByCondominiumRow, error)
	ListPendingRequestsByCondo(ctx context.Context, condominiumID uuid.UUID) ([]ListPendingRequestsByCondoRow, error)
	LogAccessEntry(ctx context.Context, arg LogAccessEntryParams) (AccessLog, error)
	RevokeInvite(ctx context.Context, arg RevokeInviteParams) error
	SaveUserDevice(ctx context.Context, arg SaveUserDeviceParams) error
	UpdateAccessRequestStatus(ctx context.Context, arg UpdateAccessRequestStatusParams) error
	UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) error
	UpdateBillStatus(ctx context.Context, arg UpdateBillStatusParams) (Bill, error)
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error)
	UpdatePackageToWithdrawn(ctx context.Context, arg UpdatePackageToWithdrawnParams) error
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error
}

var _ Querier = (*Queries)(nil)
