// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgstore

import (
	"context"
)

type Querier interface {
	CreateCondominium(ctx context.Context, arg CreateCondominiumParams) error
}

var _ Querier = (*Queries)(nil)
