// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: residents.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createResident = `-- name: CreateResident :exec
INSERT INTO residents (
  user_id,
  apartment_id,
  type,
  is_responsible
) VALUES (
  $1,
  $2,
  $3,
  $4
)
`

type CreateResidentParams struct {
	UserID        uuid.UUID `json:"user_id"`
	ApartmentID   uuid.UUID `json:"apartment_id"`
	Type          string    `json:"type"`
	IsResponsible bool      `json:"is_responsible"`
}

func (q *Queries) CreateResident(ctx context.Context, arg CreateResidentParams) error {
	_, err := q.db.Exec(ctx, createResident,
		arg.UserID,
		arg.ApartmentID,
		arg.Type,
		arg.IsResponsible,
	)
	return err
}
