// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_devices.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const getCondoAdminTokens = `-- name: GetCondoAdminTokens :many
SELECT
  d.fcm_token
FROM user_devices d
JOIN condominium_members m ON m.user_id = d.user_id
WHERE m.condominium_id = $1 AND m.role IN ('admin', 'syndic')
`

func (q *Queries) GetCondoAdminTokens(ctx context.Context, condominiumID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getCondoAdminTokens, condominiumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var fcm_token string
		if err := rows.Scan(&fcm_token); err != nil {
			return nil, err
		}
		items = append(items, fcm_token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManyTokensByApartmentId = `-- name: GetManyTokensByApartmentId :many
SELECT d.fcm_token
FROM residents r
JOIN user_devices d ON d.user_id = r.user_id
WHERE r.apartment_id = $1
`

func (q *Queries) GetManyTokensByApartmentId(ctx context.Context, apartmentID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getManyTokensByApartmentId, apartmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var fcm_token string
		if err := rows.Scan(&fcm_token); err != nil {
			return nil, err
		}
		items = append(items, fcm_token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDeviceTokens = `-- name: GetUserDeviceTokens :many
SELECT
  fcm_token
FROM user_devices
WHERE user_id = $1
`

func (q *Queries) GetUserDeviceTokens(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserDeviceTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var fcm_token string
		if err := rows.Scan(&fcm_token); err != nil {
			return nil, err
		}
		items = append(items, fcm_token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveUserDevice = `-- name: SaveUserDevice :exec
INSERT INTO user_devices (user_id, fcm_token, platform)
VALUES($1, $2, $3)
ON CONFLICT (fcm_token)
DO UPDATE SET
  user_id = EXCLUDED.user_id,
  last_used_at = NOW()
`

type SaveUserDeviceParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FcmToken string    `json:"fcm_token"`
	Platform *string   `json:"platform"`
}

func (q *Queries) SaveUserDevice(ctx context.Context, arg SaveUserDeviceParams) error {
	_, err := q.db.Exec(ctx, saveUserDevice, arg.UserID, arg.FcmToken, arg.Platform)
	return err
}
