// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Suporte Vizen",
            "email": "support@vizen.app"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/apartments": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new apartment. The user must be an **admin** or **syndic** of the condominium.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Apartments"
                ],
                "summary": "Create Apartment",
                "parameters": [
                    {
                        "description": "Apartment creation payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_controllers.CreateApartmentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Apartment successfully created",
                        "schema": {
                            "$ref": "#/definitions/api_controllers.CreateApartmentResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON payload",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "User not authenticated",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "User does not have permission",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Condominium not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    },
                    "409": {
                        "description": "Apartment already exists in this block",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ValidationErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Generates a new access token using a valid refresh token from Cookie (Web) or Body (Mobile)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh Access Token",
                "parameters": [
                    {
                        "description": "Refresh Token (Optional if using Cookies)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api_controllers.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token refreshed successfully",
                        "schema": {
                            "$ref": "#/definitions/api_controllers.RefreshTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Token not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid or expired session",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    }
                }
            }
        },
        "/condominiums": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new condominium and assigns the current user as admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Condominiums"
                ],
                "summary": "Create Condominium",
                "parameters": [
                    {
                        "description": "Condominium creation payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_controllers.CreateCondominiumRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Condominium successfully created",
                        "schema": {
                            "$ref": "#/definitions/api_controllers.CreateCondominiumResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON payload",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "User not authenticated",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "User does not have permission",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    },
                    "409": {
                        "description": "CNPJ already registered",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ValidationErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "Creates an user and account with credentials",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Create User",
                "parameters": [
                    {
                        "description": "Signup Credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_controllers.SignupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created user successfully",
                        "schema": {
                            "$ref": "#/definitions/api_controllers.SignupResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON payload",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    },
                    "409": {
                        "description": "Email already exists",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ValidationErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves detailed information about the currently logged-in user. Requires a valid Bearer Token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get Current User Profile",
                "responses": {
                    "200": {
                        "description": "User profile details",
                        "schema": {
                            "$ref": "#/definitions/api_controllers.UserProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized / Invalid Token",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    }
                }
            }
        },
        "/users/signin": {
            "post": {
                "description": "Authenticates the user and returns the Access Token. Refresh Token is returned in the Body (Mobile) or HttpOnly Cookie (Web).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User Login",
                "parameters": [
                    {
                        "description": "Login Credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_controllers.SigninWithCredentialsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "$ref": "#/definitions/api_controllers.SigninResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON payload",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ValidationErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Bellorico323_vizen_internal_api_common.ErrResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api_controllers.CreateApartmentRequest": {
            "type": "object",
            "required": [
                "condominiumId",
                "number"
            ],
            "properties": {
                "block": {
                    "type": "string"
                },
                "condominiumId": {
                    "type": "string"
                },
                "number": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "api_controllers.CreateApartmentResponse": {
            "type": "object",
            "properties": {
                "apartmentId": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api_controllers.CreateCondominiumRequest": {
            "type": "object",
            "required": [
                "address",
                "cnpj",
                "name",
                "planType"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "cnpj": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "planType": {
                    "type": "string",
                    "enum": [
                        "basic",
                        "pro",
                        "enterprise"
                    ]
                }
            }
        },
        "api_controllers.CreateCondominiumResponse": {
            "type": "object",
            "properties": {
                "condominiumId": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api_controllers.RefreshTokenRequest": {
            "type": "object",
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "api_controllers.RefreshTokenResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "api_controllers.SigninResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "api_controllers.SigninWithCredentialsRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "api_controllers.SignupRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "api_controllers.SignupResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "api_controllers.UserProfileResponse": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_Bellorico323_vizen_internal_api_common.ErrResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_Bellorico323_vizen_internal_api_common.ValidationErrResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/validator.ErrorResponse"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "validator.ErrorResponse": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Vizen API",
	Description:      "Backend server for Vizen Application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
